[project]
name = "praisonai-agent"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "openai",
    "twilio",
    "requests",
    "python-dotenv",
    "praisonai",
    "elevenlabs"
]
# Removed: virtualenvs.in-project = true
